model:
  provider: azure
  azure_deployment_name: ${AZURE_DEPLOYMENT_NAME}
  api_key: ${AZURE_API_KEY}
  endpoint: ${AZURE_ENDPOINT}
  api_version: ${AZURE_API_VERSION}

embedding:
  provider: azure
  azure_deployment_name: ${AZURE_EMBEDDING_DEPLOYMENT_NAME}
  api_key: ${AZURE_API_KEY}
  endpoint: ${AZURE_ENDPOINT}
  api_version: ${AZURE_API_VERSION}
